### ISSUE TITLE
[Feature Request] Add optional bind IP option (`--interface`) when using `curl`

### ISSUE THREAD

**Issue by taoky** [johnnychen94/StorageServer.jl#16]
When StorageMirrorServer.jl is used under an environment with multiple IPs (interfaces) from different ISPs, it could happen that upstreams (https://us-east.storage.juliahub.com and https://kr.storage.juliahub.com) are only reachable under some specific interfaces (it could happen when some ISPs block upstreams' IPs).

`curl` (as is used in v0.2.0) supports binding to a specified interface when requesting, by adding a parameter `--interface`. It can be designed that when a specific environment variable (e.g., `BIND_ADDRESS=xxx.xxx.xxx.xxx`) is set, then use it to request upstreams (`curl --interface $BIND_ADDRESS ...`). Configuring Julia's storage syncing can be more flexible if it can be implemented.

**Comment by johnnychen94** [comment]
Will be available in v0.2.1
