### ISSUE TITLE
Read CLONES_DIR and STATIC_DIR from ENV?

### ISSUE THREAD

**Issue by findmyway** [johnnychen94/StorageServer.jl#3]
Also adding a prefix of `JULIA_` would help avoid some potential conflicts.

**Comment by johnnychen94** [comment]
Let me see if I can get rid of `gen_static.jl` example and make it a one-liner script using `julia -e`, I believe this is what you expected?

**Comment by johnnychen94** [comment]
provided by 66005ae750d42c3604a4c0f8529f4e59542a1b65 (v0.1.0-beta.1)

you can use it with `]add https://github.com/johnnychen94/StorageServer.jl.git#v0.1.0-beta.1`
